from datetime import datetime
from sqlalchemy import Column, Integer, String, Float, DateTime, Boolean
from sqlalchemy.orm import declarative_base

Base = declarative_base()


class TradeRecord(Base):
    """
    Database table for storing completed and open trades.
    Persists trade data across program restarts.
    """
    __tablename__ = "trades"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String, nullable=False)
    direction = Column(String, nullable=False)  # "BUY" or "SELL"
    quantity = Column(Integer, nullable=False)
    entry_price = Column(Float, nullable=False)
    stop_loss_price = Column(Float, nullable=False)
    target_price = Column(Float, nullable=False)
    entry_time = Column(DateTime, default=datetime.now)

    exit_price = Column(Float, nullable=True)
    exit_time = Column(DateTime, nullable=True)
    exit_reason = Column(String, nullable=True)
    pnl = Column(Float, nullable=True)
    is_open = Column(Boolean, default=True)


class SignalRecord(Base):
    """
    Database table for logging every signal generated by a strategy,
    whether or not it resulted in a trade. Useful for later analysis
    of strategy behavior.
    """
    __tablename__ = "signals"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String, nullable=False)
    strategy_name = Column(String, nullable=False)
    signal = Column(String, nullable=False)  # "BUY", "SELL", "HOLD"
    price = Column(Float, nullable=False)
    timestamp = Column(DateTime, default=datetime.now)